In [2]:
import numpy as np

In [9]:
# Useful for explaining the vectorialization part
centroids = [[0, 0], [1, 1]]
points = [[-1, 2], [1, 1], [2, 4]]
numcentroids = len(centroids)
numpoints = len(points)
# gets the numbers into correct order
centroids = np.repeat([centroids], numpoints, axis = 0)
# reshapes the numbers into one array
print(centroids.size)
centroids = centroids.reshape(centroids.size).reshape((numpoints * numcentroids), 2)
print(centroids)
# reshapes the points so each centroid in the reshaped list has a matching point
points = np.repeat([points], numcentroids, axis = 1)

12
[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]]


In [11]:
square_distances = (centroids - points)**2
square_distances = square_distances.sum(axis = 2).reshape(numpoints, numcentroids)
print(square_distances)
labels = np.argmin(square_distances, axis = 1)
print("labels: " + str(labels))
total_distances = square_distances[np.linspace(0,len(square_distances)-1,len(square_distances), dtype=int), labels]
print(total_distances)
total_distances.sum()

[[ 5  5]
 [ 2  0]
 [20 10]]
labels: [0 1 1]
[ 5  0 10]


15