In [1]:
import numpy as np

In [9]:
# Useful for explaining the vectorialization part
centroids = [[0, 0], [1, 1]]
points = [[-1, 2], [1, 1], [2, 4]]
numcentroids = len(centroids)
numpoints = len(points)
# gets the numbers into correct order
centroids = np.repeat([centroids], numpoints, axis = 0)
# reshapes the numbers into one array
print(centroids.size)
centroids = centroids.reshape(centroids.size).reshape((numpoints * numcentroids), 2)
print(centroids)
# reshapes the points so each centroid in the reshaped list has a matching point
points = np.repeat([points], numcentroids, axis = 1)

12
[[0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]]


In [11]:
square_distances = (centroids - points)**2
square_distances = square_distances.sum(axis = 2).reshape(numpoints, numcentroids)
print(square_distances)
labels = np.argmin(square_distances, axis = 1)
print("labels: " + str(labels))
total_distances = square_distances[np.linspace(0,len(square_distances)-1,len(square_distances), dtype=int), labels]
print(total_distances)
total_distances.sum()

[[ 5  5]
 [ 2  0]
 [20 10]]
labels: [0 1 1]
[ 5  0 10]


15

In [2]:
class KMemes:
    def __init__(self, n_clusters, n_init):
        self.n_clusters = n_clusters
        self.n_init = n_init
        self.labels_ = []
        self.centroids = []
        self.fitted = False

    def fit(self, array):
        self.point_dimensions = np.shape(array)[1]
        self.centroids = np.random.rand(shape=(self.n_clusters, self.point_dimensions))
        self.labels_ = np.zeros(shape=(np.shape(array)[0]), dtype = int)
        self.best_distance = sys.maxsize # infinity
        self.best_iterations = 0

        for i in range(self.n_init):
            iterations = 0
            new_centroids = np.random.rand(self.n_clusters, self.point_dimensions)
            new_labels = np.zeros(shape=(np.shape(array)[0]), dtype = int)
            prev_distance = sys.maxsize

            while True:
                iterations += 1
                _new_centroids = new_centroids
                _array = array
                numcentroids = len(_new_centroids)
                numpoints = len(_array)
                _new_centroids = np.repeat([_new_centroids], numpoints, axis = 0)
                _new_centroids = _new_centroids.reshape(_new_centroids.size).reshape((numpoints * numcentroids), self.point_dimensions)
                _array = np.repeat([_array], numcentroids, axis = 1)
                square_distances = (_new_centroids - _array)**2
                square_distances = square_distances.sum(axis = 2).reshape(numpoints, numcentroids)
                new_labels = np.argmin(square_distances, axis = 1)
                current_distance = square_distances[np.linspace(0, len(square_distances)-1, len(square_distances),dtype=int), new_labels].sum()

                cluster_coordinate_sums = np.zeros((self.n_clusters, self.point_dimensions), dtype=float)
                cluster_numberof_points = np.zeros(self.n_clusters)
                np.add.at(cluster_coordinate_sums, new_labels, array)
                np.add.at(cluster_numberof_points, new_labels, 1)

                cluster_numberof_points = cluster_numberof_points.reshape(np.shape(cluster_numberof_points)[0], 1)
                new_centroids = cluster_coordinate_sums / cluster_numberof_points
                if np.abs(prev_distance - current_distance) < 10 or iterations > 100:
                    self.fitted = True
                    if current_distance < self.best_distance:
                        self.best_distance = current_distance
                        self.best_iterations = iterations
                        self.centroids = new_centroids
                        self.labels_ = new_labels
                    break
                prev_distance = current_distance


False

In [5]:
9223372036854775807 < sys.maxsize

False